image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync Bitbucket to GitHub
        script:
          - apt-get update
          - apt-get install -y git
          - git clone git clone git@bitbucket.org:ag-sound/scorm-upload-project.git
          - git remote add github https://github.com/AlejandroGispert/scorm-translator.git
          - git config user.email "alejandrobusiness2022@gmail.com"
          - git config user.name "AlejandroGispert"
          - git push github main
