image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync Bitbucket to GitHub
        script:
          - apt-get update
          - apt-get install -y git
          - git clone git clone https://ag-sound-admin@bitbucket.org/ag-sound/scorm-upload-project.git
          - cd scorm-upload-project
          - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/AlejandroGispert/scorm-translator.git
          - git config user.email "alejandrobusiness2022@gmail.com"
          - git config user.name "AlejandroGispert"
          - git push github main